version: 2
updates:
    - package-ecosystem: 'pnpm'
      directory: '/next'
      schedule:
          interval: 'monthly'
    - package-ecosystem: 'pnpm'
      directory: '/strapi'
      schedule:
          interval: 'monthly'
